---
#title: "Información sobre el curso"
toc: true
#self-contained: true
---

## Información sobre el curso

::: {.callout-note appearance="minimal" icon="false"}
## 

-   Forma parte de la oferta del [SFPIE](https://www.uv.es/sfpie){target="_blank"} de la Universitat de València. La ficha oficial del curso está [aquí]({{< var my_ficha_oficial_curso >}}){target="_blank"}.


-   En el curso usaremos 3 programas. Principalmente usaremos [R](https://cran.r-project.org/){target="_blank"} a través de [RStudio](https://www.rstudio.com/products/rstudio/download/#download){target="_blank"}. En una de las últimas sesiones del curso también usaremos [Quarto](https://quarto.org/).


-   Se recomienda tener instaladas **versiones recientes** de los 3 programas. Tienes instrucciones de instalación más abajo

-   El aula del curso no tiene ordenadores, así que es necesario acudir al curso con tu **propio ordenador**. Además, es conveniente que traigas **un ratón**: piensa que buena parte de los errores que cometeremos se deberán a la precisión en copy-paste. Evitémoslo!!

-   Los materiales que usaremos están en [Materiales](materiales.qmd).
:::


## Horario y aula

::: {.callout-note appearance="minimal" icon="false"}

{{< include _includes/_horario_curso.qmd >}}

:::



<br>

## Programas (instalación)

::: {.callout-important collapse="false" appearance="default" icon="false"}
## Instalación de R, RStudio y Quarto

-   En el curso usaremos 3 programas: R, RStudio y Quarto, así que tenemos que instalarlos

-   Has de instalar los programas en este orden:

    1.  R: <https://cran.r-project.org/>{target="_blank"}

    2.  RStudio: <https://posit.co/download/rstudio-desktop/>{target="_blank"}
    
    3. Quarto: <https://quarto.org/docs/download/>{target="_blank"}

-   Para ello, solamente has de descargar las versiones de los instaladores adecuadas para tu sistema operativo
:::



::: {.callout-important collapse="false" appearance="default" icon="false"}
## Instalación de paquetes

- En el curso también usaremos algunos paquetes de R, así que tendremos que instalarlos 

- Los paquetes se han de instalar después de haber instalado los 3 programas (R, RStudio y Quarto)

- Los paquetes [no son necesarios para el primer día del curso]{.underline}, así que, si tenéis dudas, esperaros a que Vicente os explique cómo ejecutar código R. Si aún así no sabéis cómo hacerlo, no os preocupéis, volveremos a hablar sobre ello, en clase, durante la **segunda sesión** del curso
  
:::

<br>


::: {.callout-important collapse="true" appearance="default" icon="false"}
## ¿Cómo instalar los paquetes?

- Si sabes instalarlos, perfecto!!, pero recuerda que Los paquetes no son necesarios para el primer día del curso.

- Algunos paquetes se han de compilar por lo que hay que tener las herramientas necesarias, así que:

    - Si usas Windows tendrás que instalar **Rtools**. [Aquí](https://cran.r-project.org/bin/windows/Rtools/) puedes descargarte el instalador adecuado
    
    - Si tienes un Mac, tendrás que instalar the **Xcode Command Line Tools**. Lo normal es que lo tengas ya instalado, si no fuese el caso, [aquí](https://www.makeuseof.com/install-xcode-command-line-tools/) te explican como hacerlo. Además, como nos cuentan [aquí](https://psyteachr.github.io/msc-data-skills/installingr.html), si tienes un Mac, es conveniente instalar **XQuartz**, para ello sólo tienes que buscar el instalador en <https://www.xquartz.org/>

  
- Finalmente, para instalar los paquetes que usaremos durante el curso tendremos que **ejecutar las siguientes instrucciones**:

```{r}
#| eval: false
#| code-line-numbers: false
#| code-overflow: wrap
#| code-fold: true
#| code-summary: "Código para instalar los paquetes"

#- instalación de paquetes ---------------------------------

install.packages("pak")

mys_pkgs <- c("tidyverse", "curl", "eurostat", "here", "palmerpenguins", "quantmod", "rio", "gt", "DT", "gapminder", "markdown")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("usethis", "janitor", "ggthemes", "gganimate", "sjPlot", "refugees", "slider", "repmis", "jtools", "huxtable")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("sf", "rcartocolor", "rmapshaper", "gtExtras", "patchwork", "magick")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("kableExtra", "modelsummary", "rpivotTable", "widyr", "irlba", "tmap")
pak::pkg_install(mys_pkgs)

mys_pkgs <- c("GGally", "ggtext", "maps")
pak::pkg_install(mys_pkgs)  

mys_pkgs <- c("summarytools", "glin/reactable", "agstn/dataxray", "naniar")
pak::pkg_install(mys_pkgs)  

mys_pkgs <- c("DataExplorer", "corrr", "inspectdf", "explore", "stargazer", "apaTables")
pak::pkg_install(mys_pkgs)   

mys_pkgs <- c("easystats", "plotly", "mapSpain")
pak::pkg_install(mys_pkgs)

mys_pkgs <- c("OECD", "rbioapi")
pak::pkg_install(mys_pkgs)

mys_pkgs <- c("openxlsx", "xlsx")
pak::pkg_install(mys_pkgs)

my_pkgs <- c("meme", "imager", "sctyner/memer", "devtools", "ggpol", "pxR", "mapproj", "WDI", "wbstats", "rJava")
pak::pkg_install(mys_pkgs)


mys_pkgs <- c("perezp44/pjpv.curso.R.2022", "perezp44/pjpv2020.01")
pak::pkg_install(mys_pkgs)



#- finalmente, si te instalas todos los paquetes, se instalarán 324 pkg's aprox. (q ocupan 842 MB aprox.). 
#- Si tienes problemas de espacio, siempre podrás desinstalarlos o borrarlos directamente
pkgs <- pak::pkg_list()

#- normalmente tendrás 2 librerías
.libPaths()
#- en la primera tienes los pkgs de "R-base": "C:/Program Files/R/R-4.5/library"   
#- en la segunda tienes los paquetes q se instala un usuario:  "C:/Users/Usuario/AppData/Local/R/win-library/4.5"
```

:::



::: {.callout-important collapse="true" appearance="default" icon="false"}
##  Más cosas sobre instalación R

Lo que hay en esta sección [no tienes porqué ejecutarlo]{.underline}, **es sólo para tenerlo a mano por si nos hiciese falta durante el curso**


- Para chequear qué versiones del software tienes instaladas, podemos usar **en la TERMINAL** el siguiente código:

```bash
R --version         #- 4.5
rstudio --version   #- 2025.06
quarto --version    #- 1.7
```

- Para chequear si tu sistema está preparado to build packages:

```r
devtools::has_devel()    #- Your system is ready to build packages!
```

- Para instalar `tinytext` & friends, desde **la TERMINAL**:


```bash
quarto install tool tinytext
quarto install tinytex --update-path
quarto install tool chromium
```

- Algunos chequeos (desde la TERMINAL):

```bash
quarto check install
quarto check knitr
```


- Para editar preferencias de RStudio

```r
usethis::edit_rstudio_prefs()
usethis::use_blank_slate() 
```


:::
